version: "3"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web-secured.address=:443
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "8060:8060"
    volumes:
      # listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock


  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`${DOMAIN}`) && Path(`/whoami`)
      - traefik.http.routers.whoami.entrypoints=web

  posts:
    container_name: posts
    build: posts-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.posts.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/v1/posts`)
      - traefik.http.routers.posts.entrypoints=web
