// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID      int32              `json:"id"`
	Userid  int32              `json:"userid"`
	Descr   pgtype.Text        `json:"descr"`
	Created pgtype.Timestamptz `json:"created"`
}

type Comment struct {
	ID       int64              `json:"id"`
	Userid   int32              `json:"userid"`
	Postid   int32              `json:"postid"`
	Parentid pgtype.Int4        `json:"parentid"`
	Content  pgtype.Text        `json:"content"`
	Created  pgtype.Timestamptz `json:"created"`
}

type Photo struct {
	ID      int32              `json:"id"`
	Userid  int32              `json:"userid"`
	Albumid int32              `json:"albumid"`
	Url     pgtype.Text        `json:"url"`
	Created pgtype.Timestamptz `json:"created"`
}

type Post struct {
	ID       int32              `json:"id"`
	Userid   int32              `json:"userid"`
	Created  pgtype.Timestamptz `json:"created"`
	Tags     pgtype.Text        `json:"tags"`
	Content  pgtype.Text        `json:"content"`
	Atchtype pgtype.Text        `json:"atchtype"`
	Atchid   pgtype.Int4        `json:"atchid"`
	Atchurl  pgtype.Text        `json:"atchurl"`
	Reaction []int32            `json:"reaction"`
	Cmtcount pgtype.Int4        `json:"cmtcount"`
}

type Reaction struct {
	Userid int32       `json:"userid"`
	Postid int32       `json:"postid"`
	Typ    pgtype.Text `json:"typ"`
}
