// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateReaction(ctx context.Context, arg CreateReactionParams) (Reaction, error)
	DeletePost(ctx context.Context, arg DeletePostParams) (Post, error)
	DeleteReaction(ctx context.Context, arg DeleteReactionParams) (Reaction, error)
	GetAlbum(ctx context.Context, id int32) (Album, error)
	GetAlbumByUserId(ctx context.Context, userid int32) ([]Album, error)
	GetComments(ctx context.Context, postid int32) ([]Comment, error)
	GetPhoto(ctx context.Context, id int32) (Photo, error)
	GetPhotoByUserId(ctx context.Context, userid int32) ([]Photo, error)
	GetPost(ctx context.Context, id int32) (Post, error)
	GetPostByUserId(ctx context.Context, userid int32) (interface{}, error)
	GetReaction(ctx context.Context, id int32) ([]int32, error)
	GetReactionOfUser(ctx context.Context, arg GetReactionOfUserParams) (pgtype.Text, error)
	GetReactions(ctx context.Context, postid int32) ([]Reaction, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
