apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-posts
  labels:
    {{- include "posts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "posts.selectorLabels" . | nindent 4 }}
