// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Gender    string             `json:"gender"`
	Birthdate pgtype.Date        `json:"birthdate"`
	Email     string             `json:"email"`
	Phone     pgtype.Numeric     `json:"phone"`
	Intro     pgtype.Text        `json:"intro"`
	Avatars   pgtype.Text        `json:"avatars"`
	Avatarl   pgtype.Text        `json:"avatarl"`
	Created   pgtype.Timestamptz `json:"created"`
}

type Relationship struct {
	User1   int32              `json:"user1"`
	User2   int32              `json:"user2"`
	Type    pgtype.Text        `json:"type"`
	Other   pgtype.Text        `json:"other"`
	Created pgtype.Timestamptz `json:"created"`
}
