// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"
)

type Querier interface {
	CreateProfile(ctx context.Context, arg CreateProfileParams) (int32, error)
	CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error)
	DeleteRelationship(ctx context.Context, arg DeleteRelationshipParams) (Relationship, error)
	FriendsDetail(ctx context.Context, urid int32) ([]byte, error)
	GetFriendRelationships(ctx context.Context, user1 int32) ([]Relationship, error)
	GetProfile(ctx context.Context, id int32) (Profile, error)
	GetProfileByEmail(ctx context.Context, email string) (Profile, error)
	GetRelationship(ctx context.Context, arg GetRelationshipParams) (Relationship, error)
	GetRelationshipsFrom(ctx context.Context, user1 int32) ([]Relationship, error)
	GetRelationshipsTo(ctx context.Context, user2 int32) ([]Relationship, error)
	GetRequestRelationships(ctx context.Context, user1 int32) ([]Relationship, error)
	MutualFriends(ctx context.Context, arg MutualFriendsParams) ([]int32, error)
	SearchName(ctx context.Context, arg SearchNameParams) ([]byte, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateRelationship(ctx context.Context, arg UpdateRelationshipParams) (Relationship, error)
}

var _ Querier = (*Queries)(nil)
