// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	DeleteAccount(ctx context.Context, id int32) (int64, error)
	GetAccount(ctx context.Context, id int32) (Account, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccounts(ctx context.Context) ([]Account, error)
}

var _ Querier = (*Queries)(nil)
