CREATE DATABASE profiles;
GRANT ALL PRIVILEGES ON DATABASE profiles TO program;

CREATE DATABASE posts;
GRANT ALL PRIVILEGES ON DATABASE posts TO program;

CREATE DATABASE auth;
GRANT ALL PRIVILEGES ON DATABASE auth TO program;

CREATE DATABASE stats;
GRANT ALL PRIVILEGES ON DATABASE stats TO program;

ALTER DATABASE profiles OWNER TO program;
ALTER DATABASE posts OWNER TO program;
ALTER DATABASE auth OWNER TO program;
ALTER DATABASE stats OWNER TO program;
