CREATE DATABASE profiles;
GRANT ALL PRIVILEGES ON DATABASE profiles TO program;

CREATE DATABASE posts;
GRANT ALL PRIVILEGES ON DATABASE posts TO program;

ALTER DATABASE profiles OWNER TO program;
ALTER DATABASE posts OWNER TO program;
