apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stats
  labels:
    {{- include "stats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stats.selectorLabels" . | nindent 4 }}
